### ISSUE TITLE
Gallery Takes ~8 seconds to render on iOS/ doesn't render on Android

### ISSUE THREAD

**Issue by Jakoo13** [AhmedAbdoElhawary/custom_gallery_display#10]
This package is usable on iOS, it just renders slowly. However, on Android I have ran into the issue where the gallery will not render at all, only displaying the screen in the screenshot below. Am I missing something or am I the only one? 

![Screenshot 2023-07-20 at 11 52 10 AM](https://github.com/AhmedAbdoElhawary/custom_gallery_display/assets/57853451/11342f0b-8943-492e-8aa9-5d662db95581)

**Comment by AhmedAbdoElhawary** [comment]
Try to use this package https://github.com/AhmedAbdoElhawary/image_picker_plus
